[package]
name = "dtlc"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.1.3"
codespan = "0.11.1"
codespan-reporting = "0.11.1"
lalrpop-util = { version = "0.19.6", features = ["lexer"] }
regex = "1"
anyhow = "1.0.44"

[build-dependencies]
lalrpop = "0.19.6"
